### ISSUE TITLE
Local debugging failed

### ISSUE THREAD

**Issue by jackadam1981** [jim60105/simple-poll-system#1]
Follow the setup steps.

Follow the Setup step.
It works normally in cloudflare pages.
https://simple-poll-system-duz.pages.dev/
Try local debug mode.
Modify wrangler.toml, package.json.
"Wrapper dev": "wrapper pages dev -- d1 SimplePollSystem=631aae6c-ace8-4d73-bc75-453abaad85fb -- vite -- host",
Error reported during operation:
X [ERROR] [proxy]: Debugger attached
X [ERROR] [proxy]: The CJS build of Video's Node API is deprecated See https://vitejs.dev/guide/troubleshooting.html#vite -Cjs node api detached for more details

Full log:
`PS D:\nodetest\simple-poll-system> npm run wrangler-dev
Debugger attached.
> simple-poll-system@0.0.0 wrangler-dev
> wrangler pages dev --d1 SimplePollSystem=8442edb6-d37b-47e9-948c-5081bcf98ae7 --compatibility-date=2024-01-31 -- vite --host
Debugger attached.
Debugger attached.
Running vite --host...
Sleeping 5 seconds to allow proxy process to start before attempting to automatically determine port...
To skip, specify the proxy port with --proxy.
X [ERROR] [proxy]: Debugger attached.
X [ERROR] [proxy]: The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
[proxy]: Port 5173 is in use, trying another one...
[proxy]:
  VITE v5.0.10  ready in 343 ms
[proxy]:   ➜  Local:   http://localhost:5174/
[proxy]:   ➜  Network: http://172.16.0.2:5174/
[proxy]:   ➜  Network: http://192.168.0.101:5174/
û�п���ʵ��
û�п���ʵ��
Automatically determined the proxy port to be 5174.
Compiling worker to "D:\nodetest\simple-poll-system\.wrangler\tmp\pages-hywGvn\functionsWorker-0.17642199317163954.mjs"...
✨ Compiled Worker successfully
 ⛅️ wrangler 3.24.0 (update available 3.25.0)
-------------------------------------------------------
Your worker has access to the following bindings:
- D1 Databases:
  - SimplePollSystem: simple-poll-system (8442edb6-d37b-47e9-948c-5081bcf98ae7)
  - SimplePollSystem: local-SimplePollSystem=8442edb6-d37b-47e9-948c-5081bcf98ae7 (8442edb6-d37b-47e9-948c-5081bcf98ae7)
[wrangler:inf] Ready on http://127.0.0.1:8788
⎔ Starting local server...
[wrangler-UserWorker:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-12-18",        
but you've requested "2024-01-31". Falling back to "2023-12-18"...
Features enabled by your requested compatibility date may not be available.
Upgrade to `wrangler@3.25.0` to remove this warning.`

Visit 8788:
More error logs:
`[wrangler:inf] GET /api/poll/Poll1/q3 500 Internal Server Error (22ms)
[wrangler:inf] GET /api/poll/Poll1/q2 500 Internal Server Error (24ms)                                                                
[wrangler:inf] GET /api/poll/Poll1/q1 500 Internal Server Error (27ms)                                                                
X [ERROR] Error in ProxyController: Error inside ProxyWorker

   {
    name: 'Error',
    message: 'internal error',
    stack: 'Error: internal error'
  }

[wrangler:err] Error: D1_ERROR: no such table: Poll1                                                                                  
    at D1Database._sendOrThrow (cloudflare-internal:d1-api:66:19)                                                                     
    at async D1PreparedStatement.all (cloudflare-internal:d1-api:175:29)                                                              
    at async onRequestGet (file:///D:/nodetest/simple-poll-system/functions/api/poll/[[poll]].ts:21:25)
    at async next (file:///D:/nodetest/simple-poll-system/.wrangler/tmp/pages-hywGvn/C:/Users/%E5%90%B4%E5%88%9A/AppData/Roaming/npm/node_modules/wrangler/templates/pages-template-worker.ts:161:22)
    at async Object.fetch (file:///D:/nodetest/simple-poll-system/.wrangler/tmp/pages-hywGvn/C:/Users/%E5%90%B4%E5%88%9A/AppData/Roaming/npm/node_modules/wrangler/templates/pages-template-worker.ts:180:11)
    at async jsonError (file:///D:/nodetest/simple-poll-system/.wrangler/tmp/pages-hywGvn/C:/Users/%E5%90%B4%E5%88%9A/AppData/Roaming/npm/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)
    at async jsonError2 (file:///C:/Users/%E5%90%B4%E5%88%9A/AppData/Roaming/npm/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)`

**Comment by jim60105** [comment]
> [wrangler:err] Error: D1_ERROR: no such table: Poll1

Have you created the table in your local database?

**Comment by jackadam1981** [comment]
yes 
 wrangler d1 execute simple-poll-system --local --file=./init_database.sql      
wrangler d1 execute simple-poll-system --local  --command="INSERT INTO Poll1(Key,Value,IP,Time) VALUES('q1','Cats','2a09:bac5:21b4:1246::1d2:25','Wed, 31 Jan 2024 02:45:13 GMT')"


`PS D:\nodetest\simple-poll-system> wrangler d1 execute simple-poll-system --local  --command="select * from Poll1"                                   
Debugger attached.
Debugger attached.
🌀 Mapping SQL input into an array of statements
🌀 Executing on local database simple-poll-system (8442edb6-d37b-47e9-948c-5081bcf98ae7) from .wrangler\state\v3\d1:
┌────┬──────┬───────┬─────────────────────────────┬─────────────────────────┐
│ Id       │ Key         │ Value         │ IP                                                                       │ Time                                                        │
├────┼──────┼───────┼─────────────────────────────┼─────────────────────────┤
│ 1        │ Cats        │ Cats           │ 2a09:bac5:21b4:1111::1d2:25                            │ Wed, 31 Jan 2024 02:45:13 GMT            │
├────┼──────┼───────┼─────────────────────────────┼─────────────────────────┤
│ 2        │ q1           │ Cats          │ 2a09:bac5:21b4:1111::1d2:25                             │ Wed, 31 Jan 2024 02:45:13 GMT            │
├────┼──────┼───────┼─────────────────────────────┼─────────────────────────┤
│ 3        │ q1           │ Cats          │ 2a09:bac5:21b4:1111::1d2:25                             │ Wed, 31 Jan 2024 02:45:13 GMT            │
└────┴──────┴───────┴─────────────────────────────┴─────────────────────────┘

Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...`

**Comment by jackadam1981** [comment]
I did it again and the local debugging is working properly.

Tomorrow I will continue the experiment to see which step I made a mistake.

**Comment by jackadam1981** [comment]
Re-clone the repository, it seems to be missing

wrangler d1 execute simple-poll-system --local --file=./init_database.sql

It seems that he was affected by the explanation.
Step 2: Update database_id
This step is actually only used in locally debugging,
So I didn’t pay attention to the output prompt of Step 3: Create the table:
🌀 Executing on remote database simple-poll-system (f91084f6-7f4e-4f78-bd2e-6fad52de337b):
🌀 To execute on your local development database, pass the --local flag to 'wrangler d1 execute'

It seems that README.md can be updated.

Add instructions about local debugging
